#!/usr/bin/env bash

#---------------------------------------------------------------------
usage ()
{
	cat <<EOT

${0##*/}  
    Runs the necessary local commands to switch branches and/or 
    update the bin/ submodule repo to the latest release. Afterwards, 
    you should commit the changes in the parent project's repo.

Usage:
    bin/${0##*/} [branch]
    
    Provide an optional branch from the CakePHP-Shell-Scripts repo 
    you'd like to use. Defaults to 'master' for Cake 2+.


EOT

	exit 0
}
if [ "$1" = '-h' ]; then
	usage
fi


DIR="$( cd -P "$( dirname "$0" )"/.. && pwd )"
BIN_DIR="$DIR/bin"

if [ -n "$1" ]; then
	ARG_BRANCH=$1
else
	ARG_BRANCH="master"
fi


echo "## Self-updating the bin/ submodule."
cd $BIN_DIR
git pull origin $ARG_BRANCH
cd $DIR
git add bin

echo "## Done. Please commit the staged changes."
