#!/usr/bin/env bash

#---------------------------------------------------------------------
usage ()
{
	cat <<EOT

${0##*/}
    Clears Cake caches by engaging the Cake ConsoleShell and
    instructing each configured Cache object to clear itself. This
    makes it portable across caching providers, and works just as
    well with Memcached and Redis as it does with File caching.

    Should be run from the project root folder.

Usage:
    bin/${0##*/}


EOT

	exit 0
}
if [ "$1" = '-h' ]; then
	usage
fi


DIR="$( cd -P "$( dirname "$0" )"/.. >/dev/null 2>&1 && pwd )"

echo "## Clearing cache folders.";

cat <<-'EOPHP' | bin/cake console
	use Cake\Cache\Cache;
	foreach (Cache::configured() as $key) {
		Cache::clear(false, $key);
		echo "Cleared: $key\n";
	}
	return "Done";

EOPHP


