#!/usr/bin/env bash

#---------------------------------------------------------------------
usage ()
{
	cat <<EOT

${0##*/}
    Clears Cake caches by engaging the Cake ConsoleShell and
    instructing each configured Cache object to clear itself. This
    makes it portable across caching providers, and works just as
    well with Memcached and Redis as it does with File caching.

    Should be run from the project root folder.

Usage:
    bin/${0##*/}


EOT

	exit ${1:-0}  # Exit with code 0 unless an arg is passed to the method.
}
if [ "$1" = '-h' ]; then
	usage
fi


echo "## Clearing cache folders.";

bin/cake cache clear_all

echo "## Removing DebugKit SQLite file.";

DIR="$( cd -P "$( dirname "$0" )"/.. >/dev/null 2>&1 && pwd )"
rm $DIR/tmp/debug_kit.sqlite
