#!/usr/bin/env bash

#---------------------------------------------------------------------
usage ()
{
	cat <<EOT

${0##*/}  
    Clears files from known Cake tmp directories. In particular, 
    should be run after database schema changes. Should be run 
    from the project root folder.

Usage:
    bin/${0##*/}


EOT

	exit 0
}
if [ "$1" = '-h' ]; then
	usage
fi


DIR="$( cd -P "$( dirname "$0" )"/.. && pwd )"

echo "## Clearing cache folders.";
rm -f $DIR/tmp/cache/cake_*
rm -f $DIR/tmp/cache/models/*
rm -f $DIR/tmp/cache/persistent/*
rm -f $DIR/tmp/cache/views/*
