#!/usr/bin/env php
<?php
// @ref: http://ocramius.github.io/blog/automated-code-coverage-check-for-github-pull-requests-with-travis/

//----------
function usage()
{
	$script = basename(__FILE__);
	echo <<<EOT

${script} <clover.xml> <coverage_percent>
    Uses the provided Clover XML code coverage report value to calculate
    the percentage of code covered by phpunit unit tests. Compares that
    percentage to  the provided integer value, and if coverage is lower
    than specified the script returns a non-zero value to indicate failure.

    Intended to be used with automated build systems like Travis to ensure
    code coverage remains above a designated percentage.

Usage:
    bin/${script}

    clover.xml       - Provide a filesystem path to an XML file produced
                       by PHPunit's code coverage.
    coverage_percent - An integer value between 0 and 100 represented the
                       minimum required percentage of coverage required.

EOT;

	exit(0);
}
if (isset($argv[1]) && $argv[1] == '-h') {
	usage();
}

if (!isset($argv[1])) {
	throw new InvalidArgumentException(
		'First argument missing (clover.xml file path).'
	);
}

if (!isset($argv[2])) {
	throw new InvalidArgumentException(
		'Second argument missing (integer minimum coverage percent).'
	);
}

// Set up variables.
$inputFile = $argv[1];
$percentage = min(100, max(0, (int) $argv[2]));

if (!is_readable($inputFile)) {
	throw new InvalidArgumentException(
		"Invalid input file provided: {$inputFile}"
	);
}

if (!$percentage) {
	throw new InvalidArgumentException(
		"An integer checked percentage must be given as second parameter. Value provided: {$percentage}"
	);
}

$xml = new SimpleXMLElement(file_get_contents($inputFile));
$metrics = $xml->xpath('//metrics');
$totalElements = 0;
$checkedElements = 0;

foreach ($metrics as $metric) {
	$totalElements += (int) $metric['elements'];
	$checkedElements += (int) $metric['coveredelements'];
}

$coverage = ($checkedElements / $totalElements) * 100;

echo 'Code coverage is ' . number_format($coverage, 1) . '%';

if ($coverage < $percentage) {
    echo " - Minimum accepted is {$percentage}%" . PHP_EOL;
    exit(1);
}

echo ' - OK!' . PHP_EOL;
