#!/usr/bin/env php
<?php
// Usage: In another bash script, do this:
//   eval $( bin/db-credentials.sh )
// This will populate bash variables for DB_HOST, DB_NAME, DB_USER and DB_PASS.
// See db-login.sh for a usage pattern that preserves special char escaping for DB_PASS.
//   Ref: http://stackoverflow.com/questions/16320858

// DIR="$( cd -P "$( dirname "$0" )"/.. >/dev/null 2>&1 && pwd )"
// BIN_DIR="$DIR/bin"

$dir = dirname(dirname(__FILE__)); //@TODO: Needs to be relative, otherwise we get an attempt to load `project_root/Vendor/loadsys/Config/database.php` because this actual file is composer-installed and not actuall in `/bin`.
$dbConfigFile = $dir . '/Config/database.php';
include $dbConfigFile;
$db = new DATABASE_CONFIG();

echo <<<EOD
DB_HOST="{$db->default['host']}"
DB_NAME="{$db->default['database']}"
DB_USER="{$db->default['login']}"
DB_PASS="{$db->default['password']}"
EOD;
