#!/usr/bin/env bash

#---------------------------------------------------------------------
usage ()
{
	cat <<EOT

${0##*/}
    Uses the db-credentials script to start a command line mysql
    session with the correct host, database, user and password.
    Should be run from the project root folder. Passes all command
    line arguments (except for \`--help\`) and I/O redirection to
    mysql. This script can be used as a complete replacement for
    the normal mysql command, without having to worry about
    connection credentials.

    Called without arguments, the command will log you into the
    default database used by the CakePHP app. Using I/O redirection,
    .sql files can be imported into that database as well:
    \`bin/db-login < my-file.sql\`

Usage:
    bin/${0##*/}


EOT

	exit ${1:-0}  # Exit with code 0 unless an arg is passed to the method.
}
if [ "$1" = '--help' ]; then
	usage
fi


# Holy yuck, but nothing else works!
eval $( bin/db-credentials )

# Set a custom port, if provided to us.
if [ -n "${DB_PORT}" ]; then
	PORT_CLAUSE="--port=${DB_PORT}"
fi

# Define the primary command line.
CMD="mysql --host=${DB_HOST} ${PORT_CLAUSE-} --database=${DB_DATABASE} --user=${DB_USERNAME}"

# Handle all the different ways to provide (or not provide) a password.
if [[ $DB_PASSWORD =~ " |'" ]]; then
	$CMD -p"${DB_PASSWORD}" "$@" <&0
elif [ -n "${DB_PASSWORD}" ]; then
	$CMD -p$DB_PASSWORD "$@" <&0
else
	$CMD "$@" <&0
fi
