#!/usr/bin/env bash

#---------------------------------------------------------------------
usage ()
{
	cat <<EOT

${0##*/}
    Uses the db-credentials script to start a command line mysql
    session with the correct host, database, user and password.
    Should be run from the project root folder. Passes all command
    line arguments (except for \`-h\`) to mysql.

Usage:
    bin/${0##*/}


EOT

	exit ${1:-0}  # Exit with code 0 unless an arg is passed to the method.
}
if [ "$1" = '-h' ]; then
	usage
fi


DIR="$( cd -P "$( dirname "$0" )"/.. >/dev/null 2>&1 && pwd )"
BIN_DIR="$DIR/bin"

# Holy yuck, but nothing else works!
eval $( ${BIN_DIR}/db-credentials )

# Set a custom port, if provided to us.
if [ -n "${DB_PORT}" ]; then
	PORT_CLAUSE="--port=${DB_PORT}"
else
	PORT_CLAUSE=""
fi

# Define the primary command line.
CMD="mysql --host=${DB_HOST} ${PORT_CLAUSE} --database=${DB_DATABASE} --user=${DB_USERNAME}"

# Handle all the different ways to provide (or not provide) a password.
if [[ $DB_PASSWORD =~ " |'" ]]; then
	$CMD -p"${DB_PASSWORD}" "$@"
elif [ -n "${DB_PASSWORD}" ]; then
	$CMD -p$DB_PASSWORD "$@"
else
	$CMD "$@"
fi
