#!/usr/bin/env bash

#---------------------------------------------------------------------
usage ()
{
  cat <<EOT

${0##*/}
    Convenience wrapper for running the database seed shell. The default seed file
    will always run, and if the --dev flag is given, then the dev seed file will
    also run. These files need to contain queries that won't duplicate records, and
    should only be used to guarantee that required data exists in the database.

Usage:
    bin/${0##*/} [--dev]


EOT

  exit 0
}
if [ "$1" = '-h' ]; then
  usage
fi


DIR="$( cd -P "$( dirname "$0" )"/.. >/dev/null 2>&1 && pwd )"

$DIR/Console/cake seed
if [ "$1" = '--dev' ]; then
  $DIR/Console/cake seed --dev
fi

