#!/usr/bin/env bash
# Execute phpDocumentor with a standard config file.

#---------------------------------------------------------------------
usage ()
{
	cat <<EOT

${0##*/}
    Convenience wrapper around phpDocumentor. Any additional
    arguments will be passed to phpdoc itself. By default, HTML docs
    will be generated in tmp/docs/. Depends on phpdoc being
    installed into bin/ via composer.

Usage:
    bin/${0##*/} [additional phpdoc args]

EOT

	exit ${1:-0}  # Exit with code 0 unless an arg is passed to the method.
}
if [ "$1" = '-h' ]; then
	usage
fi

DIR="$( cd -P "$( dirname "$0" )"/.. >/dev/null 2>&1 && pwd )"

bin/vagrant-exec "bin/phpdoc "$@""
