#!/usr/bin/env bash
# POST a zip of generated docs or coverage reports to loadsysdev.

#@TODO: Enforce first and second args.
PROJECT_NAME=${1:-eu-mk2}
TOKEN=${2:-foobar}
DEST_URL=http://localhost/docs-manager.php

#@TODO: Add shortcut args for "docs" and "coverage" that set paths appropriately.
#@TODO: Run the appropriate command to generate docs if output path is not already populated.

SRC_DIR=tmp/coverage/html
PROJECT_NAME=${PROJECT_NAME}-coverage

# This ensures no intermediate directories are stored in the ZIP file.
cd "$SRC_DIR"

# Send the POST request, using ZIP data fed from stdin
zip -rq8 - * | curl \
 -F "authToken=$TOKEN" \
 -F "projectName=$PROJECT_NAME" \
 -F "file=@-;filename=upload.zip;type=application/zip" \
 $DEST_URL
