#!/usr/bin/env bash
# Ref: http://stackoverflow.com/questions/8513133/how-do-i-find-all-of-the-symlinks-in-a-directory-tree
# Ref: http://stackoverflow.com/questions/4532241/linux-find-all-symlinks-of-a-given-original-file-reverse-readlink

#---------------------------------------------------------------------
usage ()
{
	cat <<EOT

${0##*/}
    Searches for symlinks pointing to a given "partial" file path in
    the specified root folder.

Usage:
    bin/${0##*/} <partial> [search dir]

	$1 = The partial file name/path for which to search. You can use grep syntax.
	$2 = The directory in which to search. If not provided, defaults to the current directory (./).

Environment Variables:
	(none)

EOT

	exit 0
}
if [ "$1" = '-h' ]; then
	usage
fi





echo "@TODO: WIP"
exit 1;





# Set variables.
DIR="$( cd -P "$( dirname "$0" )"/.. && pwd )"
BIN_DIR="$DIR/bin"
CONFIG_DIR="$DIR/Config"

DEFAULT_ENVVARS_FILE="$CONFIG_DIR/env_vars.txt"
if [ -r $DEFAULT_ENVVARS_FILE ]; then
	source "${DEFAULT_ENVVARS_FILE}"
fi

REALPATH="$( which realpath )"
if [ $? -gt 0 ]; then
	REALPATH="$( which grealpath )"
fi
if [ $? -gt 0 ]; then
	echo "!! Unable to locate the 'realpath' executable. !!"
	echo ""
	exit 1
fi


# Input processing.
if [ $1 ]; then
	ARG_PARTIAL="$1"
else
	usage
fi

if [ $2 ]; then
	ARG_SEARCH_DIR="$2"
else
	ARG_SEARCH_DIR=$DIR
fi


echo "## Searching '${ARG_SEARCH_DIR}' for '${ARG_PARTIAL}'..."

find "${ARG_SEARCH_DIR}" -type l | while 
#find "${ARG_SEARCH_DIR}" -type l -exec ${REALPATH} -q {} \; | grep "${ARG_PARTIAL}"


# Depends on `realpath` which isn't present on OS X.
#find "${ARG_SEARCH_DIR}" -type l -exec ${REALPATH} -q {} \; | grep "${ARG_PARTIAL}"

# Does a recursive folder listing, grepping for matches in the results. SUPER slow since it runs an `ls` for EVERY sub-dir and greps the results of each.
#find "${ARG_SEARCH_DIR}" -exec ls -ald {} ';' 2>/dev/null | grep '\-> ${ARG_PARTIAL}'


# Finds exact matches for a given file, but that doesn't help us quite as much.
#find -L . -samefile ~/Loadsys/Assets/cake/cake_2.3.10/lib/Cake/
