#!/usr/bin/env bash

#---------------------------------------------------------------------
usage ()
{
	cat <<EOT

${0##*/}
    Clears files from Cake's logs directory. Really only needed to
    recover disk space from aggressive logs. (A better option is to
    configure \`logrotate\` to cycle, compress and purge the files
    over time.)

    Should be run from the project root folder.

Usage:
    bin/${0##*/}


EOT

	exit ${1:-0}  # Exit with code 0 unless an arg is passed to the method.
}
if [ "$1" = '-h' ]; then
	usage
fi


DIR="$( cd -P "$( dirname "$0" )"/.. >/dev/null 2>&1 && pwd )"

echo "## Clearing logs.";
rm -f $DIR/logs/*
