#!/usr/bin/env bash

#---------------------------------------------------------------------
usage ()
{
	cat <<EOT

${0##*/}
    Convenience wrapper to run any pending Migrations. Should be
    run from the project root folder.

Usage:
    bin/${0##*/}


EOT

	exit ${1:-0}  # Exit with code 0 unless an arg is passed to the method.
}
if [ "$1" = '-h' ]; then
	usage
fi

bin/cache-clear
bin/cake migrations migrate
