#!/usr/bin/env bash

#---------------------------------------------------------------------
usage ()
{
	cat <<EOT

${0##*/}  
    Convenience wrapper to run any pending Migrations. Takes an optional 
    Migrations COMMAND (defaults to "run all") and an optional plugin 
    for which to execute migrations. Should be run from the project 
    root folder.

Usage:
    bin/${0##*/} [command] [plugin]


EOT

	exit 0
}
if [ "$1" = '-h' ]; then
	usage
fi



DIR="$( cd -P "$( dirname "$0" )"/.. && pwd )"

if [ "$1" ]; then
	OPTION=$1;
else
	OPTION="run all";
fi

if [ "$2" ]; then
	PLUGIN=$2;
else
	PLUGIN="app"
fi


if [ $PLUGIN == "app" ]; then
	PLUGIN=""
else
	PLUGIN="-p $PLUGIN"
fi

$DIR/bin/clear-cache
$DIR/Console/cake Migrations.migration $OPTION $PLUGIN
$DIR/bin/clear-cache
