#!/usr/bin/env bash

#---------------------------------------------------------------------
usage ()
{
	cat <<EOT

${0##*/}  
    Scans 'pear list -a' output to determine if the named PEAR
    package is installed on the system or not. Exits with a 0
    (zero) code if the package IS installed and 1 if the package
    is NOT installed. Will exit with 2 if the 'pear' executable
    is not available.

	This is the ugly way to accomplish this, but the "right"
	way in 'pear-installed-package' won't work because PEAR's
	source code is super crusty.

Usage:
    bin/${0##*/} package [channel]


EOT

	exit 0
}
if [ "$1" = '-h' ]; then
	usage
fi

# Bail out if PEAR isn't available to us, or no arguments were provided.
PEAR="$( which pear )"
if [ $? -gt 0 ]; then
	echo "!! The 'pear' commeand was not found on this system."
	echo ""
	exit 2
fi

if [ -n "$1" ]; then
	PACKAGE=$( basename "${1,,}" )
else
	usage
fi

if [ -n "$2" ]; then
	CHANNEL="-c $2"
else
	CHANNEL=""
fi

MATCHES=$( "$PEAR" list $CHANNEL 2>&1 | tr '[:upper:]' '[:lower:]' | grep $PACKAGE )
exit $?
