#!/usr/bin/env php
<?php
//----------
function usage()
{
	$script = basename(__FILE__);
	echo <<<EOT

${script}  
    Uses the available introspection classes that ship with PEAR to determine if the named PEAR package is installed on the system or not. Exits with a 0 (zero) code if the package IS installed and 1 if the package is NOT installed.
    
    Note that the PHP source code that makes up the PEAR package itself is not PHP 5.4 compatible and does not return correct results due to deprecation and strict warnings. The output from PEAR_Registry::packageExists() is not trustworthy.

Usage:
    bin/${script} package [channel]


EOT;

	exit(0);
}
if (isset($argv[1]) && $argv[1] == '-h') {
	usage();
}

// error_reporting(~E_DEPRECATED & ~E_STRICT);
require_once 'PEAR/Registry.php';
$r = new PEAR_Registry();
$package = $argv[1] or usage();
$channel = (!empty($argv[2]) ? $argv[2] : 'pear.php.net');
// print_r(compact('package', 'channel'));
// var_dump($r->packageExists($package, $channel));
exit ($r->packageExists($package, $channel) ? 0 : 1);
