#!/usr/bin/env bash

#---------------------------------------------------------------------
usage ()
{
	cat <<EOT

${0##*/}
    Convenience wrapper around Cake's test console command. Will
    Run the Test or Suite specified as $1.

Usage:
    bin/${0##*/} <Case or Suite> [generate coverage]

    Pass a Test Case or Suite name as the first argument.


EOT

	exit 0
}
if [ "$1" = '-h' ]; then
	usage
fi


umask a+rw

DIR="$( cd -P "$( dirname "$0" )"/.. >/dev/null 2>&1 && pwd )"
BIN_DIR="${DIR}/bin"
TMP_DIR="${DIR}/tmp"
PHPUNIT_CONFIG="Config/phpunit.xml"

if [ -n "$1" ]; then
	TESTCASE=$1
	shift  # Knock off the first argument to this script so the rest will be passed to the TestShell.
else
	TESTCASE="All"
fi

bin/clear-cache
VAGRANT_EXEC=$( which vagrant )
if mount | grep -q '^/vagrant' || $?; then  # @TODO: **OR** if command `vagrant` not found, run it directly!
	Console/cake test app $TESTCASE --configuration="${PHPUNIT_CONFIG}" "$@"
else
	vagrant ssh -c "cd /var/www; Console/cake test app $TESTCASE --configuration="${PHPUNIT_CONFIG}" "$@""
fi
