#!/usr/bin/env bash

#---------------------------------------------------------------------
usage ()
{
	cat <<EOT

${0##*/}
    Convenience wrapper around Cake's test console command. Will
    Run the Test or Suite specified as $1.

Usage:
    bin/${0##*/} <Case or Suite> [generate coverage]

    Pass a Test Case or Suite name as the first argument.


EOT

	exit 0
}
if [ "$1" = '-h' ]; then
	usage
fi


umask a+rw

DIR="$( cd -P "$( dirname "$0" )"/.. && pwd )"
BIN_DIR="${DIR}/bin"
TMP_DIR="${DIR}/tmp"
PHPUNIT_CONFIG="$DIR/Config/phpunit.xml"

if [ -n "$1" ]; then
	TESTCASE=$1
else
	TESTCASE="All"
fi

$BIN_DIR/clear-cache
$BIN_DIR/cake test app $TESTCASE --configuration="${PHPUNIT_CONFIG}" "$@"
