#!/usr/bin/env bash

#---------------------------------------------------------------------
usage ()
{
	cat <<EOT

${0##*/}
    Searches the Config/ folder for any files matching the pattern
    *.ENV.* and copies them to the same file name minus ".ENV". Should
    be run from the project root folder.

    For example, where ENV="prod":
       Config/core.prod.php -> Config/core.php
       Config/database.prod.php -> Config/database.php

Usage:
    bin/${0##*/} <ENV>


EOT

	exit 0
}
if [ "$1" = '-h' ]; then
	usage
fi


DIR="$( cd -P "$( dirname "$0" )"/.. >/dev/null 2>&1 && pwd )"
APP_DIR="${DIR}"
CONFIG_DIR="${APP_DIR}/Config";

# Select the correct env, first from command line, then environment,
# then default to production.
if [ $1 ]; then
	ARG_ENV=$1;
elif [ -n "$APP_ENV" ]; then
	ARG_ENV=$APP_ENV;
else
	ARG_ENV="prod";
fi

# Copy config files in place.
echo "## Copying config files into place for environment: $ARG_ENV";
for CFG_FILE in $( ls -1 ${CONFIG_DIR} | grep -F ".${ARG_ENV}." ); do
	cp -fv ${CONFIG_DIR}/${CFG_FILE} ${CONFIG_DIR}/${CFG_FILE/\.${ARG_ENV}/} | sed "s|${DIR}\/||g"
done
