#!/usr/bin/env bash

#---------------------------------------------------------------------
usage ()
{
	cat <<EOT

${0##*/}  
    Searches the Config/ folder for any files matching the pattern 
    *.ENV.* and copies them to the same file name minus ".ENV". Should
    be run from the project root folder.
    
    For example, where ENV="prod":
       Config/core.prod.php -> Config/core.php
       Config/database.prod.php -> Config/database.php

	Note that "dashed" config files are loaded in place, not renamed.
	So core-dev.php should be loaded by core.php when the APP_ENV=dev,
	but this script would have to be used to copy core.dev.php to
	core.php. The two methods are not entirely compatible since
	core.php is probably configured to load core-dev.php in the former
	case but would be overwritten by core.dev.php in the latter.


Usage:
    bin/${0##*/} [ENV]

    \$1 = Environment name for which to load configs. Default: $APP_ENV.

EOT

	exit 0
}
if [ "$1" = '-h' ]; then
	usage
fi


DIR="$( cd -P "$( dirname "$0" )"/.. >/dev/null 2>&1 && pwd )"
CONFIG_DIR="$DIR/Config";

# Copy config files in place
if [ $1 ]; then
	ARG_ENV=$1;
else
	ARG_ENV="$APP_ENV";
fi

echo "## Copying config files into place for environment: $ARG_ENV";
for CFG_FILE in $( ls -1 ${CONFIG_DIR} | grep -F ".${ARG_ENV}." ); do
	cp -fv ${CONFIG_DIR}/${CFG_FILE} ${CONFIG_DIR}/${CFG_FILE/\.${ARG_ENV}/} | sed "s|${DIR}\/||g"
done
