#!/usr/bin/env perl
# WIP!!!
# Replaces occurrences of "${key}" in standard input from the %replace hash below with the corresponding value.
# @TODO: Needs to be modified to work with ENV vars, or passed key-val pairs.
# Ref: http://stackoverflow.com/questions/415677/how-to-replace-placeholders-in-a-text-file#answer-415693

my %replace = ( 'dbName' => 'testdb', 'somethingElse' => 'fooBar' );
undef $/;
my $buf = <STDIN>;
$buf =~ s/\$\{$_\}/$replace{$_}/g for keys %replace;
print $buf;