#!/usr/bin/env bash

#---------------------------------------------------------------------
usage ()
{
	cat <<EOT

${0##*/}
    Ensures the PHP temp directory provided on the command line is
	created and has writeable permissions. MUST BE RUN AS ROOT,
	 typically via cron.

Usage:
    bin/${0##*/}


EOT

	exit 0
}
if [ "$1" = '-h' ]; then
	usage
fi

if [ -z "$1" ]; then
	echo '!! Must provide a path to the PHP temp directory as first argument.'
	exit 1
fi

PHP_TMP_DIR="$1"

if [ ! -d "$PHP_TMP_DIR" ]; then
	mkdir -p "$PHP_TMP_DIR"
fi

chmod -R a+rwx "$PHP_TMP_DIR"
chmod +t "$PHP_TMP_DIR"
